"""auto-vote

Revision ID: 23517ad593b1
Revises: bbc683b5c123
Create Date: 2022-11-02 18:10:40.152454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23517ad593b1'
down_revision = 'bbc683b5c123'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
