"""auto-vote

Revision ID: 2d0f4c81bb2a
Revises: bbc683b5c123
Create Date: 2022-11-02 11:54:09.068537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0f4c81bb2a'
down_revision = 'bbc683b5c123'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('posts', 'review',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('votes', sa.Column('posts_id', sa.Integer(), nullable=False))
    op.add_column('votes', sa.Column('users_id', sa.Integer(), nullable=False))
    op.drop_constraint('votes_user_id_fkey', 'votes', type_='foreignkey')
    op.drop_constraint('votes_post_id_fkey', 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'users', ['users_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'votes', 'posts', ['posts_id'], ['id'], ondelete='CASCADE')
    op.drop_column('votes', 'post_id')
    op.drop_column('votes', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('votes', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key('votes_post_id_fkey', 'votes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('votes_user_id_fkey', 'votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('votes', 'users_id')
    op.drop_column('votes', 'posts_id')
    op.alter_column('posts', 'review',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('posts', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###
