"""empty message

Revision ID: 73a1f819078a
Revises: 23517ad593b1
Create Date: 2022-11-02 18:16:06.077848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a1f819078a'
down_revision = '23517ad593b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
